### ISSUE TITLE
TypeError: 'NodeView' object does not support item assignment

### ISSUE THREAD

**Issue by SeekPoint** [benedekrozemberczki/GEMSEC#2]
mldl@ub1604:~/ub16_prj/GEMSEC$ python src/embedding_clustering.py
Model initialization started.
Traceback (most recent call last):
  File "src/embedding_clustering.py", line 22, in <module>
    create_and_run_model(args)
  File "src/embedding_clustering.py", line 11, in create_and_run_model
    model = GEMSECWithRegularization(args, graph)
  File "/home/mldl/ub16_prj/GEMSEC/src/model.py", line 32, in __init__
    self.degrees, self.walks = self.walker.do_walks()
  File "/home/mldl/ub16_prj/GEMSEC/src/calculation_helper.py", line 155, in do_walks
    random.shuffle(self.nodes)
  File "/usr/lib/python2.7/random.py", line 291, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'NodeView' object does not support item assignment

**Comment by benedekrozemberczki** [comment]
I suppose Your networkx version differs. What is your nx version?

**Comment by SeekPoint** [comment]
sure, it works
