### ISSUE TITLE
how to solve this problem?

### ISSUE THREAD

**Issue by ghost** [benedekrozemberczki/GEMSEC#6]
when I run the example script in the readme, it raise the error

```
Model initialization started.
Traceback (most recent call last):
  File "src/embedding_clustering.py", line 22, in <module>
    create_and_run_model(args)
  File "src/embedding_clustering.py", line 11, in create_and_run_model
    model = GEMSECWithRegularization(args, graph)
  File "/data1/huangzp/GEMSEC/src/model.py", line 32, in __init__
    self.degrees, self.walks = self.walker.do_walks()
  File "/data1/huangzp/GEMSEC/src/calculation_helper.py", line 167, in do_walks
    random.shuffle(self.nodes)
  File "/opt/anaconda2/envs/python3/lib/python3.6/random.py", line 275, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'NodeView' object does not support item assignment
```

**Comment by benedekrozemberczki** [comment]
You habe a different version of networkx.
