### ISSUE TITLE
error on model DeepWalk

### ISSUE THREAD

**Issue by SeekPoint** [benedekrozemberczki/GEMSEC#7]
python src/embedding_clustering.py --model DeepWalk
..... 

be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
2018-12-30 14:51:33.065695: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-12-30 14:51:33.149835: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-30 14:51:33.150255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.38GiB
2018-12-30 14:51:33.150270: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-12-30 14:51:33.339045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-30 14:51:33.339081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-12-30 14:51:33.339089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-12-30 14:51:33.339301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10039 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Model Initialized.

Epoch 1. initiated.

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5908/5908 [00:16<00:00, 361.82it/s]

Traceback (most recent call last):
  File "src/embedding_clustering.py", line 22, in <module>
    create_and_run_model(args)
  File "src/embedding_clustering.py", line 18, in create_and_run_model
    model.train()
  File "/home/ub16c9/ub16_prj/GEMSEC/src/model.py", line 150, in train
    self.modularity_score, assignments = classical_modularity_calculator(self.graph, self.final_embeddings, self.args)
  File "/home/ub16c9/ub16_prj/GEMSEC/src/calculation_helper.py", line 125, in classical_modularity_calculator
    modularity = community.modularity(assignments,graph)
  File "/home/ub16c9/ub16_prj/GEMSEC/.venv/lib/python3.5/site-packages/community/community_louvain.py", line 119, in modularity
    com = partition[node]
KeyError: 0
(.venv) ub16c9@ub16c9-gpu:~/ub16_prj/GEMSEC$

**Comment by benedekrozemberczki** [comment]
The Python-Louvain API was changed, I changed a typing now it seems fine.
